### ISSUE TITLE
Non working notifications when path prefix defined

### ISSUE THREAD

**Issue by igogold** [spantaleev/vaultwarden-docker-ansible-deploy#3]
If '_devture_vaultwarden_path_prefix_' variable defined (as `/some-prefix`, without trailing slash), the rule

``devture_vaultwarden_container_labels_traefik_rule_websocket: 'Host(`{{ devture_vaultwarden_server_fqn }}`) && Path(`{{ devture_vaultwarden_path_prefix | quote }}notifications/hub`)'``

 in the '_roles/custom/devture_vaultwarden/defaults/main.yml_' creates path without / delimiter, so label file for traefik has such line:

``traefik.http.routers.vaultwarden-vaultwarden-websocket.rule=Host(`vaultwarden.domain.com`) && Path(`/some-prefixnotifications/hub`)``

which not works then.

> ###########################################################
> '/notifications/hub' should be proxied to the websocket server or notifications won't work.
> Go to the Wiki for more info, or disable WebSockets setting WEBSOCKET_ENABLED=false.
> ###########################################################################################

I don't know correct workaround if '_devture_vaultwarden_path_prefix_' is '/' so there is no pull request.

**Comment by spantaleev** [comment]
Thanks for catching and reporting this! It should be fixed now.
